### ISSUE TITLE
Wechaty Puppet Implementation NPM checklist

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet#125]
- [ ] `wechaty-puppet` must not a dependency. It should be put in devDependencies and peerDependencies 
- [ ] `wechaty` must not a dependency. It should be put in devDependencies and peerDependencies 
- [ ] must exist `examples/ding-dong-bot.ts` to implement the ding/dong logic, use puppet api only.

**Comment by huan** [comment]
Merge to https://wechaty.js.org/docs/specifications/puppet
